baseURL = "https://krshrimali.github.io"
title   = "Kushashwa Ravi Shrimali (Kush)"

DefaultContentLanguage = "en"

themesDir = "themes"
theme = "PaperMod"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-146662543-1"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

# [author]
#   name = "Kushashwa Ravi Shrimali"

[blackfriday]
  hrefTargetBlank = true

[outputFormats]
[outputFormats.TOML]
mediaType = "application/toml"

[outputs]
  home = ["HTML", "RSS", "TOML", "JSON"]

[taxonomies]
  tag      = "tags"
  category = "categories"
  author   = "author"
  search   = "search"

[params]
  # Theme parameters
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  disableSpecial1stPost = true

  # Home page settings - commented out to show posts directly
  # [params.homeInfoParams]
  #   Title = "Kushashwa Ravi Shrimali (Kush)"
  #   Content = "Find some of my profiles below"

  # Social icons
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/kushashwa"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:kushashwaravishrimali@gmail.com"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kushashwa-ravi-shrimali-b6780152/"
  [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/2218021/kushashwa-ravi-shrimali"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/krshrimali"

  # Metadata
  description = "Welcome to Kushashwa's blog"
  keywords = ["blog", "developer", "personal"]

  # Content directory
  contentTypeName = "posts"

[params.search]
  enable = true
  backend = "fuse" # can be stork or fuse

[params.author]
  name = "Kushashwa Ravi Shrimali"

# Webmentions configuration (if needed in the future)
# [params.webmention]
#   enabled = false

# Comments system
[params.comments]
  enabled = true

# Code highlighting
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = "monokai"

# Old social icons have been replaced with params.socialIcons above

[languages]
  [languages.en]
    [languages.en.params]
      subtitle  = "Learning never stops!"
      weight    = 1
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # [languages.fr]
    # subtitle  = "Hello Friend NG HZ Theme"
    # weight    = 2
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "search"
    name       = "Search"
    url        = "/search/"
    weight     = 10
  [[menu.other]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
  [[menu.other]]
    identifier = "categories"
    name       = "Categories"
    url        = "/categories"

# https://gohugo.io/getting-started/configuration-markup/#table-of-contents
[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# Ignore warnings about raw HTML in markdown
ignoreLogs = ['warning-goldmark-raw-html']
