name: PR Validation

on:
  pull_request:
    branches:
      - main  # Set this to the branch you want to validate PRs against

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Check build status
        run: |
          if [ $? -eq 0 ]; then
            echo "Build successful!"
          else
            echo "Build failed!"
            exit 1
          fi